name: corporita_task
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  arcore_flutter_plugin:
  camera:
  pytorch_lite: ^4.2.4
  tflite_flutter: ^0.10.4
  flutter_vision: ^1.1.4
  tflite: ^1.1.2
  hive: ^2.2.3
  build_runner: ^2.4.8
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  flutter_bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true

  assets:
    - assets/models/
    - assets/labels/
    - assets/images/
    - assets/img.png